class Solution(object):
    def permute(self, nums):
        """
        :type nums: List[int]
        :rtype: List[List[int]]
        Input: nums = [1,2,3]
        Output: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]
        Question: Can you generate all possible permutations of the given list of numbers?
        Approach:
        - Use a recursive approach to generate all possible permutations.
        - For each element in the list, remove it and generate all permutations of the remaining elements.
        - Append the removed element to each of these permutations.
        - Collect all these permutations in the result array.
        Time Complexity: O(n!)
        Space Complexity: O(n) (due to recursion stack)
        Example:
        - Input: nums = [1,2,3]
        - Output: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]
        Explanation:
        - For the input [1,2,3], the permutations are generated by recursively selecting each element and generating permutations of the remaining elements.
        - This process continues until all elements have been used as the first element in the permutation, resulting in all possible permutations being generated.
        - The final result array contains all possible permutations of the input list.
        - For example, for the input [1,2,3], the permutations are generated as follows:
          1. Select 1 as the first element, then generate permutations of [2,3] -> [1,2,3], [1,3,2]
          2. Select 2 as the first element, then generate permutations of [1,3] -> [2,1,3], [2,3,1]
          3. Select 3 as the first element, then generate permutations of [1,2] -> [3,1,2], [3,2,1]
          This illustrates how the recursive approach generates all possible permutations by selecting each element as the first element and generating permutations of the remaining elements.
        Steps:
        1. create result array which will hold all possible permutations
        2. if len(nums) == 1 ie. there is only 1 element in nums array then return all of the elements from nums array
        3. traverse nums array by index:
            - pop out number from nums array at index 0
            - do recursion on remaining numbers and assign results of that to temp stack
            - traverse temp stack
                - put popped number in temp stack
            - extend temp stack in result array
            - put back number in nums array
        4. return result
        """
        res = []
        if len(nums) == 1:
            return [nums[:]]
        
        for i in range(len(nums)):
            n = nums.pop(0)
            perms = self.permute(nums)
            for perm in perms:
                perm.append(n)
            res.extend(perms)
            nums.append(n)
        return res